In [11]:
import numpy as np

In [12]:
arr = np.array([10,20,30])

In [13]:
arr

array([10, 20, 30])

In [14]:
arr1 = np.array([[10,20,30],[30,85,56],[98,56,78]])

In [15]:
arr1

array([[10, 20, 30],
       [30, 85, 56],
       [98, 56, 78]])

In [20]:
arr2 = np.zeros((5,5))

In [23]:
arr2

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [24]:
type(arr2)

numpy.ndarray

In [25]:
arr2 = np.zeros((10,10))

In [26]:
arr2

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [28]:
arr2 = np.full((5,5),7)

In [29]:
arr2

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [31]:
arr3 = np.arange(5,20)

In [32]:
arr3

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [33]:
arr3 = np.arange(10,50,5)

In [34]:
arr3

array([10, 15, 20, 25, 30, 35, 40, 45])

In [35]:
arr3 = np.random.randint(1,100,9)

In [36]:
arr3

array([20, 95, 12,  2, 42, 85, 93, 64, 63])

In [37]:
arr3 = np.array([[1,2,3],[4,5,6]])

In [38]:
arr3.shape

(2, 3)

In [39]:
arr3

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
arr3.shape= (3,2)

In [41]:
arr3

array([[1, 2],
       [3, 4],
       [5, 6]])

In [42]:
arr1 = np.array([10,20,30])

In [43]:
arr2 = np.array([40,50,60])

In [44]:
np.vstack((arr1,arr2))

array([[10, 20, 30],
       [40, 50, 60]])

In [45]:
n1 = np.array([15,20,98])

In [46]:
n2 = np.array([23,5,78])

In [47]:
np.hstack((n1,n2))

array([15, 20, 98, 23,  5, 78])

In [48]:
n3 = np.array([15,56,75])

In [49]:
n4 = np.array([17,19,65])

In [50]:
np.column_stack((n3,n4))

array([[15, 17],
       [56, 19],
       [75, 65]])

In [51]:
arr6 = ([10,20,30,40,50,60])

In [52]:
arr7 = ([50,60,70,80,90])

In [53]:
np.intersect1d(arr6,arr7)

array([50, 60])

In [54]:
np.setdiff1d(arr6,arr7)

array([10, 20, 30, 40])

In [55]:
np.setdiff1d(arr7,arr6)

array([70, 80, 90])

In [56]:
n1 = np.array([10,20])

In [57]:
n2 = np.array([30,40])

In [58]:
np.sum([n1,n2])

100

In [59]:
np.sum([n1,n2], axis = 0)

array([40, 60])

In [60]:
np.sum([n1,n2], axis = 1)

array([30, 70])

In [62]:
n1 = np.array([10,20,30])
n1 = n1+1

In [63]:
n1

array([11, 21, 31])

In [64]:
n1 = n1-1
n1

array([10, 20, 30])

In [65]:
n1 = n1*2
n1

array([20, 40, 60])

In [66]:
n1 = n1/2
n1

array([10., 20., 30.])

In [67]:
n6 = np.array([10,20,30,40,50,60,70])

In [68]:
np.mean(n6)

40.0

In [79]:
n7 = np.array([10,20,30,40,50,60,70])

In [80]:
np.median(n7)

40.0

In [81]:
n8 = np.array([1,5,3,100,4,48])

In [82]:
np.std(n8)

36.59424666377065

In [86]:
n9 = np.array([10,22,30,40,50])
np.save('my_numpy', n9)

In [87]:
n10 = np.load('my_numpy.npy')

In [88]:
n10

array([10, 22, 30, 40, 50])